---
all:
  hosts:
    localhost:
      ansible_connection: local
  children:
    revpi:
      hosts:
        RevPi_Connect_5-94366:
          ansible_host: RevPi94366.local
          ansible_user: pi
          ansible_password: "{{ revpi_devices[inventory_hostname].password }}"
          ansible_become_pass: "{{ ansible_password }}"
          revpi_model: RevPi_Connect_5
          revpi_serial: "{{ revpi_devices[inventory_hostname].sn }}"
          revpi_mac: "{{ revpi_devices[inventory_hostname].mac }}"
    laser_nodes:
      hosts:
        RevPi_Connect_5-94366:
